/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMyCertificatesRouteImport } from './routes/_authenticated/my-certificates'
import { Route as AuthenticatedMyCoursesRouteImport } from './routes/_authenticated/my-courses'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as CertificateCodeRouteImport } from './routes/certificate.$code'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin/certificates'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminEnrollmentsRouteImport } from './routes/_authenticated/admin/enrollments'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated/admin/organizations'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedInstructorCoursesRouteImport } from './routes/_authenticated/instructor/courses'
import { Route as AuthenticatedInstructorStudentsRouteImport } from './routes/_authenticated/instructor/students'
import { Route as AuthenticatedInstructorSubmissionsRouteImport } from './routes/_authenticated/instructor/submissions'
import { Route as AuthenticatedLearnCourseIdRouteImport } from './routes/_authenticated/learn.$courseId'
import { Route as AuthenticatedStudentCertificatesRouteImport } from './routes/_authenticated/student/certificates'
import { Route as AuthenticatedStudentCoursesRouteImport } from './routes/_authenticated/student/courses'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student/profile'
import { Route as AuthenticatedInstructorCoursesCourseIdRouteImport } from './routes/_authenticated/instructor/courses_.$courseId'
import { Route as AuthenticatedInstructorCoursesNewRouteImport } from './routes/_authenticated/instructor/courses_.new'
import { Route as AuthenticatedStudentCoursesCourseIdRouteImport } from './routes/_authenticated/student/courses_.$courseId'
import { Route as AuthenticatedStudentQuizzesQuizIdRouteImport } from './routes/_authenticated/student/quizzes.$quizId'
import { Route as AuthenticatedInstructorCoursesCourseIdAnalyticsRouteImport } from './routes/_authenticated/instructor/courses_.$courseId.analytics'
import { Route as AuthenticatedInstructorCoursesCourseIdBuilderRouteImport } from './routes/_authenticated/instructor/courses_.$courseId.builder'
import { Route as AuthenticatedInstructorCoursesCourseIdStudentsRouteImport } from './routes/_authenticated/instructor/courses_.$courseId.students'
import { Route as AuthenticatedStudentCoursesCourseIdLessonsLessonIdRouteImport } from './routes/_authenticated/student/courses_.$courseId.lessons.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyCertificatesRoute =
  AuthenticatedMyCertificatesRouteImport.update({
    id: '/my-certificates',
    path: '/my-certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyCoursesRoute = AuthenticatedMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CertificateCodeRoute = CertificateCodeRouteImport.update({
  id: '/certificate/$code',
  path: '/certificate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnrollmentsRoute =
  AuthenticatedAdminEnrollmentsRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedInstructorCoursesRoute =
  AuthenticatedInstructorCoursesRouteImport.update({
    id: '/instructor/courses',
    path: '/instructor/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorStudentsRoute =
  AuthenticatedInstructorStudentsRouteImport.update({
    id: '/instructor/students',
    path: '/instructor/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorSubmissionsRoute =
  AuthenticatedInstructorSubmissionsRouteImport.update({
    id: '/instructor/submissions',
    path: '/instructor/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnCourseIdRoute =
  AuthenticatedLearnCourseIdRouteImport.update({
    id: '/learn/$courseId',
    path: '/learn/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCertificatesRoute =
  AuthenticatedStudentCertificatesRouteImport.update({
    id: '/student/certificates',
    path: '/student/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCoursesRoute =
  AuthenticatedStudentCoursesRouteImport.update({
    id: '/student/courses',
    path: '/student/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/student/profile',
    path: '/student/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorCoursesCourseIdRoute =
  AuthenticatedInstructorCoursesCourseIdRouteImport.update({
    id: '/instructor/courses_/$courseId',
    path: '/instructor/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorCoursesNewRoute =
  AuthenticatedInstructorCoursesNewRouteImport.update({
    id: '/instructor/courses_/new',
    path: '/instructor/courses/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdRoute =
  AuthenticatedStudentCoursesCourseIdRouteImport.update({
    id: '/student/courses_/$courseId',
    path: '/student/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentQuizzesQuizIdRoute =
  AuthenticatedStudentQuizzesQuizIdRouteImport.update({
    id: '/student/quizzes/$quizId',
    path: '/student/quizzes/$quizId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorCoursesCourseIdAnalyticsRoute =
  AuthenticatedInstructorCoursesCourseIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedInstructorCoursesCourseIdRoute,
  } as any)
const AuthenticatedInstructorCoursesCourseIdBuilderRoute =
  AuthenticatedInstructorCoursesCourseIdBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => AuthenticatedInstructorCoursesCourseIdRoute,
  } as any)
const AuthenticatedInstructorCoursesCourseIdStudentsRoute =
  AuthenticatedInstructorCoursesCourseIdStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedInstructorCoursesCourseIdRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute =
  AuthenticatedStudentCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthenticatedStudentCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-certificates': typeof AuthenticatedMyCertificatesRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/instructor/courses': typeof AuthenticatedInstructorCoursesRoute
  '/instructor/students': typeof AuthenticatedInstructorStudentsRoute
  '/instructor/submissions': typeof AuthenticatedInstructorSubmissionsRoute
  '/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
  '/student/certificates': typeof AuthenticatedStudentCertificatesRoute
  '/student/courses': typeof AuthenticatedStudentCoursesRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/instructor/courses/$courseId': typeof AuthenticatedInstructorCoursesCourseIdRouteWithChildren
  '/instructor/courses/new': typeof AuthenticatedInstructorCoursesNewRoute
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRouteWithChildren
  '/student/quizzes/$quizId': typeof AuthenticatedStudentQuizzesQuizIdRoute
  '/instructor/courses/$courseId/analytics': typeof AuthenticatedInstructorCoursesCourseIdAnalyticsRoute
  '/instructor/courses/$courseId/builder': typeof AuthenticatedInstructorCoursesCourseIdBuilderRoute
  '/instructor/courses/$courseId/students': typeof AuthenticatedInstructorCoursesCourseIdStudentsRoute
  '/student/courses/$courseId/lessons/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-certificates': typeof AuthenticatedMyCertificatesRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/instructor/courses': typeof AuthenticatedInstructorCoursesRoute
  '/instructor/students': typeof AuthenticatedInstructorStudentsRoute
  '/instructor/submissions': typeof AuthenticatedInstructorSubmissionsRoute
  '/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
  '/student/certificates': typeof AuthenticatedStudentCertificatesRoute
  '/student/courses': typeof AuthenticatedStudentCoursesRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/instructor/courses/$courseId': typeof AuthenticatedInstructorCoursesCourseIdRouteWithChildren
  '/instructor/courses/new': typeof AuthenticatedInstructorCoursesNewRoute
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRouteWithChildren
  '/student/quizzes/$quizId': typeof AuthenticatedStudentQuizzesQuizIdRoute
  '/instructor/courses/$courseId/analytics': typeof AuthenticatedInstructorCoursesCourseIdAnalyticsRoute
  '/instructor/courses/$courseId/builder': typeof AuthenticatedInstructorCoursesCourseIdBuilderRoute
  '/instructor/courses/$courseId/students': typeof AuthenticatedInstructorCoursesCourseIdStudentsRoute
  '/student/courses/$courseId/lessons/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-certificates': typeof AuthenticatedMyCertificatesRoute
  '/_authenticated/my-courses': typeof AuthenticatedMyCoursesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/_authenticated/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/instructor/courses': typeof AuthenticatedInstructorCoursesRoute
  '/_authenticated/instructor/students': typeof AuthenticatedInstructorStudentsRoute
  '/_authenticated/instructor/submissions': typeof AuthenticatedInstructorSubmissionsRoute
  '/_authenticated/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
  '/_authenticated/student/certificates': typeof AuthenticatedStudentCertificatesRoute
  '/_authenticated/student/courses': typeof AuthenticatedStudentCoursesRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/instructor/courses_/$courseId': typeof AuthenticatedInstructorCoursesCourseIdRouteWithChildren
  '/_authenticated/instructor/courses_/new': typeof AuthenticatedInstructorCoursesNewRoute
  '/_authenticated/student/courses_/$courseId': typeof AuthenticatedStudentCoursesCourseIdRouteWithChildren
  '/_authenticated/student/quizzes/$quizId': typeof AuthenticatedStudentQuizzesQuizIdRoute
  '/_authenticated/instructor/courses_/$courseId/analytics': typeof AuthenticatedInstructorCoursesCourseIdAnalyticsRoute
  '/_authenticated/instructor/courses_/$courseId/builder': typeof AuthenticatedInstructorCoursesCourseIdBuilderRoute
  '/_authenticated/instructor/courses_/$courseId/students': typeof AuthenticatedInstructorCoursesCourseIdStudentsRoute
  '/_authenticated/student/courses_/$courseId/lessons/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/admin'
    | '/dashboard'
    | '/my-certificates'
    | '/my-courses'
    | '/notifications'
    | '/profile'
    | '/certificate/$code'
    | '/courses/$slug'
    | '/courses/'
    | '/admin/audit'
    | '/admin/audit-logs'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/organizations'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/instructor/courses'
    | '/instructor/students'
    | '/instructor/submissions'
    | '/learn/$courseId'
    | '/student/certificates'
    | '/student/courses'
    | '/student/profile'
    | '/admin/'
    | '/instructor/courses/$courseId'
    | '/instructor/courses/new'
    | '/student/courses/$courseId'
    | '/student/quizzes/$quizId'
    | '/instructor/courses/$courseId/analytics'
    | '/instructor/courses/$courseId/builder'
    | '/instructor/courses/$courseId/students'
    | '/student/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/dashboard'
    | '/my-certificates'
    | '/my-courses'
    | '/notifications'
    | '/profile'
    | '/certificate/$code'
    | '/courses/$slug'
    | '/courses'
    | '/admin/audit'
    | '/admin/audit-logs'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/organizations'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/instructor/courses'
    | '/instructor/students'
    | '/instructor/submissions'
    | '/learn/$courseId'
    | '/student/certificates'
    | '/student/courses'
    | '/student/profile'
    | '/admin'
    | '/instructor/courses/$courseId'
    | '/instructor/courses/new'
    | '/student/courses/$courseId'
    | '/student/quizzes/$quizId'
    | '/instructor/courses/$courseId/analytics'
    | '/instructor/courses/$courseId/builder'
    | '/instructor/courses/$courseId/students'
    | '/student/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-certificates'
    | '/_authenticated/my-courses'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/certificate/$code'
    | '/courses/$slug'
    | '/courses/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/enrollments'
    | '/_authenticated/admin/organizations'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/users'
    | '/_authenticated/instructor/courses'
    | '/_authenticated/instructor/students'
    | '/_authenticated/instructor/submissions'
    | '/_authenticated/learn/$courseId'
    | '/_authenticated/student/certificates'
    | '/_authenticated/student/courses'
    | '/_authenticated/student/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/instructor/courses_/$courseId'
    | '/_authenticated/instructor/courses_/new'
    | '/_authenticated/student/courses_/$courseId'
    | '/_authenticated/student/quizzes/$quizId'
    | '/_authenticated/instructor/courses_/$courseId/analytics'
    | '/_authenticated/instructor/courses_/$courseId/builder'
    | '/_authenticated/instructor/courses_/$courseId/students'
    | '/_authenticated/student/courses_/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyRoute: typeof VerifyRoute
  CertificateCodeRoute: typeof CertificateCodeRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-certificates': {
      id: '/_authenticated/my-certificates'
      path: '/my-certificates'
      fullPath: '/my-certificates'
      preLoaderRoute: typeof AuthenticatedMyCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-courses': {
      id: '/_authenticated/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof AuthenticatedMyCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/certificate/$code': {
      id: '/certificate/$code'
      path: '/certificate/$code'
      fullPath: '/certificate/$code'
      preLoaderRoute: typeof CertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enrollments': {
      id: '/_authenticated/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/organizations': {
      id: '/_authenticated/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/instructor/courses': {
      id: '/_authenticated/instructor/courses'
      path: '/instructor/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof AuthenticatedInstructorCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor/students': {
      id: '/_authenticated/instructor/students'
      path: '/instructor/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof AuthenticatedInstructorStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor/submissions': {
      id: '/_authenticated/instructor/submissions'
      path: '/instructor/submissions'
      fullPath: '/instructor/submissions'
      preLoaderRoute: typeof AuthenticatedInstructorSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$courseId': {
      id: '/_authenticated/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof AuthenticatedLearnCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/certificates': {
      id: '/_authenticated/student/certificates'
      path: '/student/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof AuthenticatedStudentCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/courses': {
      id: '/_authenticated/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof AuthenticatedStudentCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor/courses_/$courseId': {
      id: '/_authenticated/instructor/courses_/$courseId'
      path: '/instructor/courses/$courseId'
      fullPath: '/instructor/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedInstructorCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor/courses_/new': {
      id: '/_authenticated/instructor/courses_/new'
      path: '/instructor/courses/new'
      fullPath: '/instructor/courses/new'
      preLoaderRoute: typeof AuthenticatedInstructorCoursesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/courses_/$courseId': {
      id: '/_authenticated/student/courses_/$courseId'
      path: '/student/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/quizzes/$quizId': {
      id: '/_authenticated/student/quizzes/$quizId'
      path: '/student/quizzes/$quizId'
      fullPath: '/student/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedStudentQuizzesQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor/courses_/$courseId/analytics': {
      id: '/_authenticated/instructor/courses_/$courseId/analytics'
      path: '/analytics'
      fullPath: '/instructor/courses/$courseId/analytics'
      preLoaderRoute: typeof AuthenticatedInstructorCoursesCourseIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedInstructorCoursesCourseIdRoute
    }
    '/_authenticated/instructor/courses_/$courseId/builder': {
      id: '/_authenticated/instructor/courses_/$courseId/builder'
      path: '/builder'
      fullPath: '/instructor/courses/$courseId/builder'
      preLoaderRoute: typeof AuthenticatedInstructorCoursesCourseIdBuilderRouteImport
      parentRoute: typeof AuthenticatedInstructorCoursesCourseIdRoute
    }
    '/_authenticated/instructor/courses_/$courseId/students': {
      id: '/_authenticated/instructor/courses_/$courseId/students'
      path: '/students'
      fullPath: '/instructor/courses/$courseId/students'
      preLoaderRoute: typeof AuthenticatedInstructorCoursesCourseIdStudentsRouteImport
      parentRoute: typeof AuthenticatedInstructorCoursesCourseIdRoute
    }
    '/_authenticated/student/courses_/$courseId/lessons/$lessonId': {
      id: '/_authenticated/student/courses_/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/student/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedStudentCoursesCourseIdRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEnrollmentsRoute: typeof AuthenticatedAdminEnrollmentsRoute
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
    AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
    AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminEnrollmentsRoute: AuthenticatedAdminEnrollmentsRoute,
    AuthenticatedAdminOrganizationsRoute: AuthenticatedAdminOrganizationsRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedInstructorCoursesCourseIdRouteChildren {
  AuthenticatedInstructorCoursesCourseIdAnalyticsRoute: typeof AuthenticatedInstructorCoursesCourseIdAnalyticsRoute
  AuthenticatedInstructorCoursesCourseIdBuilderRoute: typeof AuthenticatedInstructorCoursesCourseIdBuilderRoute
  AuthenticatedInstructorCoursesCourseIdStudentsRoute: typeof AuthenticatedInstructorCoursesCourseIdStudentsRoute
}

const AuthenticatedInstructorCoursesCourseIdRouteChildren: AuthenticatedInstructorCoursesCourseIdRouteChildren =
  {
    AuthenticatedInstructorCoursesCourseIdAnalyticsRoute:
      AuthenticatedInstructorCoursesCourseIdAnalyticsRoute,
    AuthenticatedInstructorCoursesCourseIdBuilderRoute:
      AuthenticatedInstructorCoursesCourseIdBuilderRoute,
    AuthenticatedInstructorCoursesCourseIdStudentsRoute:
      AuthenticatedInstructorCoursesCourseIdStudentsRoute,
  }

const AuthenticatedInstructorCoursesCourseIdRouteWithChildren =
  AuthenticatedInstructorCoursesCourseIdRoute._addFileChildren(
    AuthenticatedInstructorCoursesCourseIdRouteChildren,
  )

interface AuthenticatedStudentCoursesCourseIdRouteChildren {
  AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute: typeof AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute
}

const AuthenticatedStudentCoursesCourseIdRouteChildren: AuthenticatedStudentCoursesCourseIdRouteChildren =
  {
    AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute:
      AuthenticatedStudentCoursesCourseIdLessonsLessonIdRoute,
  }

const AuthenticatedStudentCoursesCourseIdRouteWithChildren =
  AuthenticatedStudentCoursesCourseIdRoute._addFileChildren(
    AuthenticatedStudentCoursesCourseIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyCertificatesRoute: typeof AuthenticatedMyCertificatesRoute
  AuthenticatedMyCoursesRoute: typeof AuthenticatedMyCoursesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedInstructorCoursesRoute: typeof AuthenticatedInstructorCoursesRoute
  AuthenticatedInstructorStudentsRoute: typeof AuthenticatedInstructorStudentsRoute
  AuthenticatedInstructorSubmissionsRoute: typeof AuthenticatedInstructorSubmissionsRoute
  AuthenticatedLearnCourseIdRoute: typeof AuthenticatedLearnCourseIdRoute
  AuthenticatedStudentCertificatesRoute: typeof AuthenticatedStudentCertificatesRoute
  AuthenticatedStudentCoursesRoute: typeof AuthenticatedStudentCoursesRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedInstructorCoursesCourseIdRoute: typeof AuthenticatedInstructorCoursesCourseIdRouteWithChildren
  AuthenticatedInstructorCoursesNewRoute: typeof AuthenticatedInstructorCoursesNewRoute
  AuthenticatedStudentCoursesCourseIdRoute: typeof AuthenticatedStudentCoursesCourseIdRouteWithChildren
  AuthenticatedStudentQuizzesQuizIdRoute: typeof AuthenticatedStudentQuizzesQuizIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyCertificatesRoute: AuthenticatedMyCertificatesRoute,
  AuthenticatedMyCoursesRoute: AuthenticatedMyCoursesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedInstructorCoursesRoute: AuthenticatedInstructorCoursesRoute,
  AuthenticatedInstructorStudentsRoute: AuthenticatedInstructorStudentsRoute,
  AuthenticatedInstructorSubmissionsRoute:
    AuthenticatedInstructorSubmissionsRoute,
  AuthenticatedLearnCourseIdRoute: AuthenticatedLearnCourseIdRoute,
  AuthenticatedStudentCertificatesRoute: AuthenticatedStudentCertificatesRoute,
  AuthenticatedStudentCoursesRoute: AuthenticatedStudentCoursesRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedInstructorCoursesCourseIdRoute:
    AuthenticatedInstructorCoursesCourseIdRouteWithChildren,
  AuthenticatedInstructorCoursesNewRoute:
    AuthenticatedInstructorCoursesNewRoute,
  AuthenticatedStudentCoursesCourseIdRoute:
    AuthenticatedStudentCoursesCourseIdRouteWithChildren,
  AuthenticatedStudentQuizzesQuizIdRoute:
    AuthenticatedStudentQuizzesQuizIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyRoute: VerifyRoute,
  CertificateCodeRoute: CertificateCodeRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
